import {
	Angry,
	Anxious,
	Comfortable,
	Flutter,
	Funny,
	Gloomy,
	Happy,
	Lonely,
	Proud,
	Pleased,
	Sad,
	Tired,
} from '@/assets';
import { EmotionDetail, EmotionKey } from '../types';

export const EMOTIONS: Record<EmotionKey, EmotionDetail> = {
	happy: {
		icon: Happy,
		color: 'bg-happy',
		noun: '행복',
		label: '행복한',
		value: 'happy',
	},
	good: {
		icon: Pleased,
		color: 'bg-pleased',
		noun: '기분 좋음',
		label: '기분좋은',
		value: 'good',
	},
	joyful: {
		icon: Funny,
		color: 'bg-funny',
		noun: '즐거움',
		label: '즐거운',
		value: 'joyful',
	},
	excited: {
		icon: Flutter,
		color: 'bg-flutter',
		noun: '설렘',
		label: '설레는',
		value: 'excited',
	},
	proud: {
		icon: Proud,
		color: 'bg-proud',
		noun: '뿌듯',
		label: '뿌듯한',
		value: 'proud',
	},
	calm: {
		icon: Comfortable,
		color: 'bg-comfortable',
		noun: '편안',
		label: '편안한',
		value: 'calm',
	},
	tired: {
		icon: Tired,
		color: 'bg-tired',
		noun: '피곤',
		label: '피곤한',
		value: 'tired',
	},
	lonely: {
		icon: Lonely,
		color: 'bg-lonely',
		noun: '외로움',
		label: '외로운',
		value: 'lonely',
	},
	sad: {
		icon: Sad,
		color: 'bg-sad',
		noun: '슬픔',
		label: '슬픈',
		value: 'sad',
	},
	down: {
		icon: Gloomy,
		color: 'bg-gloomy',
		noun: '우울',
		label: '우울한',
		value: 'down',
	},
	worried: {
		icon: Anxious,
		color: 'bg-anxious',
		noun: '불안',
		label: '불안한',
		value: 'worried',
	},
	angry: {
		icon: Angry,
		color: 'bg-angry',
		noun: '화남',
		label: '화난',
		value: 'angry',
	},
};
